---
version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 50
    allow:
      - dependency-name: "*"
        dependency-type: all
